GET http://localhost:5000/items

###

POST http://localhost:5000/items
Content-Type: application/json

{
    "title": "testtitle2",
    "category": "testcategory",
    "price": 2,
    "thumbnail": "testthumbnail",
    "images": ["images","2"],
    "brand": "testbrand",
    "description": "testdescription"
}
###

GET http://localhost:5000/user


###

GET http://localhost:5000/user/666883f8d4ba60f02dfa5b05

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "username":"userservice-test",
    "email":"testservice@mail.com",
    "password":"servicepassword"
}



###

PATCH http://localhost:5000/items/6659db87ca58f59594e85527
Content-Type: application/json

{
    "title":"NOVO PROMENJEN NASLOV22223"
}

###
DELETE http://localhost:5000/items/6659db87ca58f59594e85527